// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mongo/mongo.proto

package mongo_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Activation struct {
	//ID        primitive.ObjectID `json:"id" bson:"_id"`
	//Timestamp time.Time
	User                 int64    `protobuf:"varint,1,opt,name=User,proto3" json:"User,omitempty"`
	Activator            int64    `protobuf:"varint,2,opt,name=Activator,proto3" json:"Activator,omitempty"`
	Complete             bool     `protobuf:"varint,3,opt,name=Complete,proto3" json:"Complete,omitempty"`
	Retry                bool     `protobuf:"varint,4,opt,name=Retry,proto3" json:"Retry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Activation) Reset()         { *m = Activation{} }
func (m *Activation) String() string { return proto.CompactTextString(m) }
func (*Activation) ProtoMessage()    {}
func (*Activation) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba181f2c3670a70a, []int{0}
}

func (m *Activation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activation.Unmarshal(m, b)
}
func (m *Activation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activation.Marshal(b, m, deterministic)
}
func (m *Activation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activation.Merge(m, src)
}
func (m *Activation) XXX_Size() int {
	return xxx_messageInfo_Activation.Size(m)
}
func (m *Activation) XXX_DiscardUnknown() {
	xxx_messageInfo_Activation.DiscardUnknown(m)
}

var xxx_messageInfo_Activation proto.InternalMessageInfo

func (m *Activation) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *Activation) GetActivator() int64 {
	if m != nil {
		return m.Activator
	}
	return 0
}

func (m *Activation) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

func (m *Activation) GetRetry() bool {
	if m != nil {
		return m.Retry
	}
	return false
}

type ActivationInsertResult struct {
	InsertId             string   `protobuf:"bytes,1,opt,name=InsertId,proto3" json:"InsertId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivationInsertResult) Reset()         { *m = ActivationInsertResult{} }
func (m *ActivationInsertResult) String() string { return proto.CompactTextString(m) }
func (*ActivationInsertResult) ProtoMessage()    {}
func (*ActivationInsertResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba181f2c3670a70a, []int{1}
}

func (m *ActivationInsertResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivationInsertResult.Unmarshal(m, b)
}
func (m *ActivationInsertResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivationInsertResult.Marshal(b, m, deterministic)
}
func (m *ActivationInsertResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivationInsertResult.Merge(m, src)
}
func (m *ActivationInsertResult) XXX_Size() int {
	return xxx_messageInfo_ActivationInsertResult.Size(m)
}
func (m *ActivationInsertResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivationInsertResult.DiscardUnknown(m)
}

var xxx_messageInfo_ActivationInsertResult proto.InternalMessageInfo

func (m *ActivationInsertResult) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func init() {
	proto.RegisterType((*Activation)(nil), "mongo_proto.Activation")
	proto.RegisterType((*ActivationInsertResult)(nil), "mongo_proto.ActivationInsertResult")
}

func init() { proto.RegisterFile("proto/mongo/mongo.proto", fileDescriptor_ba181f2c3670a70a) }

var fileDescriptor_ba181f2c3670a70a = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xcd, 0xcf, 0x4b, 0x87, 0x92, 0x7a, 0x60, 0x11, 0x21, 0x6e, 0x30, 0x27, 0x1e,
	0xcc, 0x51, 0x2a, 0xe0, 0xe2, 0x72, 0x4c, 0x2e, 0xc9, 0x2c, 0x4b, 0x2c, 0xc9, 0xcc, 0xcf, 0x13,
	0x12, 0xe2, 0x62, 0x09, 0x2d, 0x4e, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0xb3,
	0x85, 0x64, 0xb8, 0x38, 0xa1, 0x2a, 0xf2, 0x8b, 0x24, 0x98, 0xc0, 0x12, 0x08, 0x01, 0x21, 0x29,
	0x2e, 0x0e, 0xe7, 0xfc, 0xdc, 0x82, 0x9c, 0xd4, 0x92, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x8e,
	0x20, 0x38, 0x5f, 0x48, 0x84, 0x8b, 0x35, 0x28, 0xb5, 0xa4, 0xa8, 0x52, 0x82, 0x05, 0x2c, 0x01,
	0xe1, 0x28, 0x99, 0x70, 0x89, 0x21, 0x6c, 0xf4, 0xcc, 0x2b, 0x4e, 0x2d, 0x2a, 0x09, 0x4a, 0x2d,
	0x2e, 0xcd, 0x29, 0x01, 0x99, 0x05, 0xe1, 0x7b, 0xa6, 0x80, 0x5d, 0xc0, 0x19, 0x04, 0xe7, 0x1b,
	0x45, 0x72, 0xb1, 0xfa, 0x82, 0x9c, 0x2d, 0x14, 0xc0, 0x25, 0x00, 0x11, 0x44, 0x72, 0xb6, 0xb8,
	0x1e, 0x92, 0x97, 0xf4, 0x10, 0x12, 0x52, 0xca, 0x38, 0x24, 0x90, 0xad, 0x4d, 0x62, 0x03, 0xcb,
	0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xf0, 0xcb, 0x31, 0x31, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MongoClient is the client API for Mongo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MongoClient interface {
	InsertActivation(ctx context.Context, in *Activation, opts ...grpc.CallOption) (*ActivationInsertResult, error)
}

type mongoClient struct {
	cc *grpc.ClientConn
}

func NewMongoClient(cc *grpc.ClientConn) MongoClient {
	return &mongoClient{cc}
}

func (c *mongoClient) InsertActivation(ctx context.Context, in *Activation, opts ...grpc.CallOption) (*ActivationInsertResult, error) {
	out := new(ActivationInsertResult)
	err := c.cc.Invoke(ctx, "/mongo_proto.Mongo/InsertActivation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MongoServer is the server API for Mongo service.
type MongoServer interface {
	InsertActivation(context.Context, *Activation) (*ActivationInsertResult, error)
}

// UnimplementedMongoServer can be embedded to have forward compatible implementations.
type UnimplementedMongoServer struct {
}

func (*UnimplementedMongoServer) InsertActivation(ctx context.Context, req *Activation) (*ActivationInsertResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertActivation not implemented")
}

func RegisterMongoServer(s *grpc.Server, srv MongoServer) {
	s.RegisterService(&_Mongo_serviceDesc, srv)
}

func _Mongo_InsertActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Activation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoServer).InsertActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongo_proto.Mongo/InsertActivation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoServer).InsertActivation(ctx, req.(*Activation))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mongo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mongo_proto.Mongo",
	HandlerType: (*MongoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertActivation",
			Handler:    _Mongo_InsertActivation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongo/mongo.proto",
}
